### PR TITLE
Rename AccessListItem field name

### PR DESCRIPTION
**Pull request by zjb0807**
Closes: #34

### CODE REVIEW

**Comment by zjb0807** [comment]
Maybe rename `slots` to `storageKeys` is better.
@tgmichel @sorpaas How do you think it?

**Comment by sorpaas** [comment]
I have no objections, but in that case you'll need to bump the minor version.

**Comment by zjb0807** [comment]
> I have no objections, but in that case you'll need to bump the minor version.

Ok. I'll do it in another PR. The PR as the patch for 0.11.1

**Comment by sorpaas** [comment]
Hmm no sorry. On a second look the TypeInfo change is also not backward compatible. So in all cases you'll have to bump the minor version.

**Comment by zjb0807** [comment]
How about using #36 instead of this PR?

**Pull request closed without merging**
