### PR TITLE
chore: upgrade crate `ethereum-types` and `rlp`

### PR DESCRIPTION
**Pull request by 0xbillw**

### CODE REVIEW

**Comment by nazar-pc** [comment]
This is needed for https://github.com/polkadot-evm/frontier upgrade to polkadot-sdk release `stable-2412`.
@sorpaas could you take a look, please?

**Comment by koushiro** [comment]
@0xbillw please fix the clippy warnings

**Comment by 0xbillw** [comment]
> @0xbillw please fix the clippy warnings

Sorry, I just saw the message. It has been processed, thank you!

**Review by koushiro — APPROVED** [review]

**Comment by 0xbillw** [comment]
> This is needed for https://github.com/polkadot-evm/frontier upgrade to polkadot-sdk release `stable-2412`. @sorpaas could you take a look, please?

@nazar-pc Do you know that [frontier](https://github.com/polkadot-evm/frontier/tree/11f8340b3146cb205fc0b10e028ee1335a637105) plans to upgrade `polkadot-sdk` to release `stable2412`? 
Currently, `frontier` is based on [stable2409](https://github.com/polkadot-evm/frontier/blob/11f8340b3146cb205fc0b10e028ee1335a637105/Cargo.toml#L86), but this version has a memory leak issue, as mentioned here: https://github.com/paritytech/polkadot-sdk/pull/5998 and https://github.com/paritytech/polkadot-sdk/issues/6149. 
But now, I am trying to upgrade frontier to `stable2412`.

**Comment by boundless-forest** [comment]
@0xbillw Try to raise an upgrade PR in the Frontier; I'll review and merge it.

**Comment by nazar-pc** [comment]
I've been working on upgrade PR, but got stuck on this. Will open later today.

**Comment by nazar-pc** [comment]
@koushiro would it be possible to release a new version of the crate with this, please?

**Comment by koushiro** [comment]
@nazar-pc Sorry, I don't have permission to publish this crate, only write permission to this repo.

Based on what I've observed so far, this crate is primarily used in projects within the Polkadot ecosystem.
Perhaps it would be more appropriate to migrate this repo to the primitives part of frontier.

**Comment by nazar-pc** [comment]
From the name of the crate it makes sense for it to live under this org, but no strong preference here from me.

@sorpaas looks like you were publishing this before, would appreciate if you can find a minute to do so again.

**Comment by 0xbillw** [comment]
> @0xbillw Try to raise an upgrade PR in the Frontier; I'll review and merge it.

@boundless-forest Sorry, I just noticed your message. I just initiated a [PR](https://github.com/polkadot-evm/frontier/pull/1595), and I'm not sure if my code is appropriate. I appreciate your guidance, thank you!

**Pull request merged**
